name: 'GA4 Event'
description: 'A GitHub Action for sending offline events to Google Analytics 4 from your repository workflows.'
inputs:
  event-name:
    description: 'The name of the event'
    required: false
    default: 'update_github'
  measurement-id:
    description: 'The measurement id for your GA4 property'
    required: true
  api-secret:
    description: 'The API secret for you GA4 property'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.event-name}}
    - ${{inputs.measurement-id}}
    - ${{inputs.api-secret}}
    - ${{github.repository}}
    - ${{github.sha}}
    - ${{github.event.head_commit.message}}
